name: "InkBridge"
description: "A lightweight App to capture Home-Assistant dashboard screenshots and optimize them for eInk displays."
version: "1.0.0"
slug: "inkbridge"
url: https://github.com/Skaronator/InkBridge
init: false
arch:
  - aarch64
  - amd64
ports:
  4521/tcp: 4521
options:
  global:
    host: "0.0.0.0"
    port: 4521
    width: 1600
    height: 1200
    colorscheme: BWGBRY
    dither_mode: FLOYD_STEINBERG
    cron_schedule: "* * * * *"
  pages: []
schema:
  global:
    host: str
    port: "int(1,65535)"
    width: "int(1,10000)"
    height: "int(1,10000)"
    colorscheme: list(MONO|BWR|BWY|BWRY|BWGBRY|GRAYSCALE_4)
    dither_mode: list(NONE|BURKES|ORDERED|FLOYD_STEINBERG|ATKINSON|STUCKI|SIERRA|SIERRA_LITE|JARVIS_JUDICE_NINKE)
    cron_schedule: str
  pages:
    - slug: str
      url: url
      width: "int?"
      height: "int?"
      colorscheme: list(MONO|BWR|BWY|BWRY|BWGBRY|GRAYSCALE_4)?
      dither_mode: list(NONE|BURKES|ORDERED|FLOYD_STEINBERG|ATKINSON|STUCKI|SIERRA|SIERRA_LITE|JARVIS_JUDICE_NINKE)?
